### ISSUE TITLE
Found null character written out

### ISSUE THREAD

**Issue by managan** [jmikeowen/spheral#17]
The output from spheral/src/Distributed/RedistributeNodes.cc, line 843 contains a null character.
Here is an example with the offending character converted to \00
SpaceFillingCurveRedistributeNodes: INITIAL node distribution statistics:
    (min, max, avg) nodes per domain: (223, 2423, 1996)
    (min, max, avg) work per domain : (223, 2423, 1996.75)\00
SpaceFillingCurveRedistributeNodes: FINAL node distribution statistics:
    (min, max, avg) nodes per domain: (1993, 1997, 1996)
    (min, max, avg) work per domain : (1993, 1997, 1996.75)\00

This makes several linux program feel the output is binary instead of text.

**Comment by jmikeowen** [comment]
Looks like you guys don't want std::ends to appear in strings meant for humans.  I agree, and this is resolved in commit 22149d9170182cc89f36438f092d459ce4e51bfe.
